[package]
name = "cond-code"
version = "0.0.1"
authors = ["devcexx"]
edition = "2018"

[lib]
name = "cond_code"
path = "src/lib.rs"
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
