unstable_features = true
comment_width = 100
edition = "2018"
format_strings = true
match_block_trailing_comma = false
max_width = 100
merge_imports = true
newline_style = "Unix"
trailing_comma = "Never"
wrap_comments = true
